"""PDF portfolio report generation using reportlab."""
import asyncio
import io
from datetime import date, datetime, timezone

import yfinance as yf
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import Response
from reportlab.graphics.charts.piecharts import Pie
from reportlab.graphics.shapes import Drawing, Rect
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    BaseDocTemplate,
    Frame,
    HRFlowable,
    PageTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)

from app.dependencies import require_manager
from app.services.supabase_client import get_supabase_admin

router = APIRouter()

# ── Professional colour palette ───────────────────────────────────────────────
_NAVY      = colors.HexColor("#0F2057")   # header banner
_ACCENT    = colors.HexColor("#4F8CFF")   # blue accent / links
_GREEN     = colors.HexColor("#059669")   # gain
_RED       = colors.HexColor("#DC2626")   # loss
_YELLOW    = colors.HexColor("#D97706")   # dividend
_PAGE_BG   = colors.HexColor("#F8FAFC")   # page background
_CARD_BG   = colors.HexColor("#FFFFFF")   # card white
_SECTION   = colors.HexColor("#EFF6FF")   # section header fill
_ROW_ALT   = colors.HexColor("#F1F5F9")   # alternate table row
_BORDER    = colors.HexColor("#CBD5E1")   # table borders
_TEXT      = colors.HexColor("#0F172A")   # body text
_MUTED     = colors.HexColor("#64748B")   # labels / captions
_WHITE     = colors.white

CHART_COLORS = [
    colors.HexColor("#4F8CFF"),
    colors.HexColor("#10B981"),
    colors.HexColor("#F59E0B"),
    colors.HexColor("#EF4444"),
    colors.HexColor("#8B5CF6"),
    colors.HexColor("#F97316"),
    colors.HexColor("#06B6D4"),
]


def _fetch_price(symbol: str) -> float | None:
    # Symbols are stored with exchange suffix already (e.g. RELIANCE.NS, TATASTEEL.BO)
    try:
        ticker = yf.Ticker(symbol)
        info = ticker.fast_info
        price = getattr(info, "last_price", None)
        if price:
            return float(price)
        hist = ticker.history(period="1d")
        if not hist.empty:
            return float(hist["Close"].iloc[-1])
    except Exception:
        pass
    return None


def _build_pie(labels: list[str], values: list[float], width: float = 180, height: float = 180) -> Drawing:
    d = Drawing(width, height)
    pie = Pie()
    pie.x = width // 2 - 65
    pie.y = height // 2 - 65
    pie.width = 130
    pie.height = 130
    pie.data = values
    pie.labels = None
    pie.sideLabels = 0
    pie.simpleLabels = 0
    for i in range(len(values)):
        pie.slices[i].fillColor = CHART_COLORS[i % len(CHART_COLORS)]
        pie.slices[i].strokeColor = colors.white
        pie.slices[i].strokeWidth = 2
        pie.slices[i].popout = 3 if i == 0 else 0
    d.add(pie)
    return d


def _section_header(title: str, styles) -> Table:
    """Styled section header with left accent bar."""
    p = Paragraph(f"<b>{title.upper()}</b>", ParagraphStyle(
        "SH", parent=styles["Normal"],
        textColor=_NAVY, fontSize=9,
        fontName="Helvetica-Bold", letterSpacing=1,
    ))
    tbl = Table([[p]], colWidths=[17 * cm])
    tbl.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), _SECTION),
        ("LEFTPADDING",   (0, 0), (-1, -1), 10),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 8),
        ("TOPPADDING",    (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LINEAFTER",     (0, 0), (0, 0),  3, _ACCENT),   # thin top border
        ("LINEABOVE",     (0, 0), (-1, 0), 0.5, _BORDER),
        ("LINEBELOW",     (0, 0), (-1, 0), 0.5, _BORDER),
        ("ROUNDEDCORNERS", [4]),
    ]))
    return tbl


def _header_footer(canvas, doc):
    """Draws the navy banner header and page footer on every page."""
    W, H = A4
    canvas.saveState()

    # ── Top banner ──────────────────────────────────────────────────
    banner_h = 2.4 * cm
    canvas.setFillColor(_NAVY)
    canvas.rect(0, H - banner_h, W, banner_h, fill=1, stroke=0)

    # Accent stripe at bottom of banner
    canvas.setFillColor(_ACCENT)
    canvas.rect(0, H - banner_h - 3, W, 3, fill=1, stroke=0)

    # Brand name
    canvas.setFont("Helvetica-Bold", 16)
    canvas.setFillColor(_WHITE)
    canvas.drawString(1.8 * cm, H - banner_h + 0.65 * cm, "InsightfulPortfolio")

    # "PORTFOLIO REPORT" tag on the right
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.HexColor("#93C5FD"))
    canvas.drawRightString(W - 1.8 * cm, H - banner_h + 0.65 * cm, "PORTFOLIO REPORT")

    # ── Footer ───────────────────────────────────────────────────────
    canvas.setFillColor(_MUTED)
    canvas.setFont("Helvetica", 7)
    canvas.drawString(1.8 * cm, 0.8 * cm,
        f"Generated by InsightfulPortfolio  ·  {datetime.now(timezone.utc).strftime('%B %d, %Y')}  ·  Prices are indicative")
    canvas.drawRightString(W - 1.8 * cm, 0.8 * cm, f"Page {doc.page}")

    # Thin top footer line
    canvas.setStrokeColor(_BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(1.8 * cm, 1.2 * cm, W - 1.8 * cm, 1.2 * cm)

    canvas.restoreState()


def _generate_pdf(
    manager_name: str,
    client: dict,
    holdings: list[dict],
    transactions: list[dict],
    live_prices: dict[str, float],
) -> bytes:
    buf = io.BytesIO()
    W, H = A4

    doc = BaseDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=1.8 * cm,
        rightMargin=1.8 * cm,
        topMargin=3.2 * cm,    # space for banner
        bottomMargin=1.8 * cm,
    )
    frame = Frame(doc.leftMargin, doc.bottomMargin,
                  doc.width, doc.height, id="main")
    doc.addPageTemplates([PageTemplate(id="all", frames=frame, onPage=_header_footer)])

    styles = getSampleStyleSheet()
    story = []

    # ── Styles ────────────────────────────────────────────────────────────────
    body = ParagraphStyle("Body", parent=styles["Normal"], textColor=_TEXT, fontSize=9, leading=14)
    label_st = ParagraphStyle("Label", parent=styles["Normal"], textColor=_MUTED, fontSize=8)
    small = ParagraphStyle("Small", parent=styles["Normal"], textColor=_MUTED, fontSize=7.5, leading=11)

    report_date = datetime.now(timezone.utc).strftime("%B %d, %Y")

    # ── Client info card ──────────────────────────────────────────────────────
    info_data = [
        [
            Paragraph(f"<font color='#64748B' size='7'>CLIENT</font><br/>"
                      f"<b><font size='11'>{client.get('full_name','—')}</font></b>", body),
            Paragraph(f"<font color='#64748B' size='7'>EMAIL</font><br/>"
                      f"<font size='9'>{client.get('email','—')}</font>", body),
            Paragraph(f"<font color='#64748B' size='7'>MANAGED BY</font><br/>"
                      f"<font size='9'>{manager_name}</font>", body),
            Paragraph(f"<font color='#64748B' size='7'>REPORT DATE</font><br/>"
                      f"<font size='9'>{report_date}</font>", body),
        ]
    ]
    info_tbl = Table(info_data, colWidths=[4.5*cm, 5*cm, 4*cm, 3.5*cm])
    info_tbl.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), _CARD_BG),
        ("BOX",           (0, 0), (-1, -1), 0.8, _BORDER),
        ("LEFTPADDING",   (0, 0), (-1, -1), 12),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 8),
        ("TOPPADDING",    (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("LINEBEFORE",    (1, 0), (-1, -1), 0.5, _BORDER),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(info_tbl)
    story.append(Spacer(1, 14))

    # ── KPI summary ───────────────────────────────────────────────────────────
    invested_value = sum(h["quantity"] * h["avg_cost"] for h in holdings)
    current_value = 0.0
    for h in holdings:
        lp = live_prices.get(h["symbol"]) or h.get("manual_price") or h["avg_cost"]
        current_value += h["quantity"] * lp

    returns = current_value - invested_value
    returns_pct = (returns / invested_value * 100) if invested_value else 0.0
    gain = returns >= 0
    ret_color = "#059669" if gain else "#DC2626"
    ret_arrow = "▲" if gain else "▼"

    def _kpi_cell(label: str, value: str, color: str = "#0F172A") -> Paragraph:
        return Paragraph(
            f"<font color='#64748B' size='7'>{label}</font><br/>"
            f"<font name='Helvetica-Bold' size='14' color='{color}'>{value}</font>",
            body,
        )

    kpi_data = [[
        _kpi_cell("INVESTED VALUE",  f"₹{invested_value:,.0f}"),
        _kpi_cell("CURRENT VALUE",   f"₹{current_value:,.0f}"),
        _kpi_cell("TOTAL RETURNS",   f"{ret_arrow} ₹{abs(returns):,.0f}", ret_color),
        _kpi_cell("RETURN %",        f"{ret_arrow} {abs(returns_pct):.2f}%", ret_color),
    ]]
    kpi_tbl = Table(kpi_data, colWidths=[4.25 * cm] * 4)
    kpi_tbl.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (1, 0), _CARD_BG),
        ("BACKGROUND",    (2, 0), (3, 0), colors.HexColor("#F0FDF4") if gain else colors.HexColor("#FEF2F2")),
        ("BOX",           (0, 0), (-1, -1), 0.8, _BORDER),
        ("LINEBEFORE",    (1, 0), (-1, -1), 0.5, _BORDER),
        ("LEFTPADDING",   (0, 0), (-1, -1), 14),
        ("TOPPADDING",    (0, 0), (-1, -1), 12),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 12),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(_section_header("Portfolio Summary", styles))
    story.append(Spacer(1, 6))
    story.append(kpi_tbl)
    story.append(Spacer(1, 16))

    # ── Asset Allocation ──────────────────────────────────────────────────────
    if holdings:
        type_values: dict[str, float] = {}
        for h in holdings:
            lp = live_prices.get(h["symbol"]) or h.get("manual_price") or h["avg_cost"]
            t = h.get("asset_type", "other").replace("_", " ").title()
            type_values[t] = type_values.get(t, 0) + h["quantity"] * lp

        total_cv = sum(type_values.values()) or 1
        labels = list(type_values.keys())
        pcts  = [v / total_cv * 100 for v in type_values.values()]
        vals  = list(type_values.values())

        pie_drawing = _build_pie(labels, pcts)

        # Legend rows
        legend_rows = []
        for i, (lbl, pct, val) in enumerate(zip(labels, pcts, vals)):
            hex_col = CHART_COLORS[i % len(CHART_COLORS)].hexval()[2:]
            legend_rows.append([
                Paragraph(f"<font color='#{hex_col}' size='11'>■</font>  "
                          f"<font size='8'>{lbl}</font>", body),
                Paragraph(f"<b>{pct:.1f}%</b>", body),
                Paragraph(f"₹{val:,.0f}", small),
            ])

        legend_tbl = Table(legend_rows, colWidths=[3.8*cm, 1.4*cm, 3.3*cm])
        legend_tbl.setStyle(TableStyle([
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("TOPPADDING",    (0, 0), (-1, -1), 5),
            ("LINEBELOW",     (0, 0), (-1, -2), 0.3, _BORDER),
            ("TEXTCOLOR",     (1, 0), (1, -1), _TEXT),
            ("TEXTCOLOR",     (2, 0), (2, -1), _MUTED),
            ("ALIGN",         (1, 0), (-1, -1), "RIGHT"),
        ]))

        # Wrap pie + legend in a card
        alloc_inner = Table([[pie_drawing, legend_tbl]], colWidths=[8*cm, 9*cm])
        alloc_inner.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                                          ("LEFTPADDING", (1, 0), (1, 0), 16)]))
        alloc_card = Table([[alloc_inner]], colWidths=[17*cm])
        alloc_card.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, -1), _CARD_BG),
            ("BOX",           (0, 0), (-1, -1), 0.8, _BORDER),
            ("TOPPADDING",    (0, 0), (-1, -1), 10),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
            ("LEFTPADDING",   (0, 0), (-1, -1), 10),
        ]))
        story.append(_section_header("Asset Allocation", styles))
        story.append(Spacer(1, 6))
        story.append(alloc_card)
        story.append(Spacer(1, 16))

    # ── Holdings Table ────────────────────────────────────────────────────────
    if holdings:
        h_headers = ["Symbol", "Type", "Qty", "Avg Cost", "Cur. Price", "Value", "P&L"]
        h_rows = [h_headers]
        h_pl_signs = []
        for h in holdings:
            sym = h["symbol"]
            lp  = live_prices.get(sym) or h.get("manual_price") or h["avg_cost"]
            val = h["quantity"] * lp
            pl  = val - h["quantity"] * h["avg_cost"]
            h_pl_signs.append(pl >= 0)
            h_rows.append([
                sym.replace(".NS", "").replace(".BO", ""),
                h.get("asset_type", "—").replace("_", " ").title(),
                f"{h['quantity']:g}",
                f"₹{h['avg_cost']:,.2f}",
                f"₹{lp:,.2f}",
                f"₹{val:,.0f}",
                f"{'▲' if pl>=0 else '▼'} ₹{abs(pl):,.0f}",
            ])

        col_w = [3.0, 2.4, 1.6, 2.6, 2.6, 2.6, 2.2]
        h_tbl = Table(h_rows, colWidths=[w*cm for w in col_w])
        h_style = [
            ("BACKGROUND",    (0, 0), (-1, 0), _NAVY),
            ("TEXTCOLOR",     (0, 0), (-1, 0), _WHITE),
            ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE",      (0, 0), (-1, 0), 8),
            ("FONTSIZE",      (0, 1), (-1, -1), 8),
            ("TEXTCOLOR",     (0, 1), (-1, -1), _TEXT),
            ("ALIGN",         (0, 0), (-1, 0), "CENTER"),
            ("ALIGN",         (2, 1), (-1, -1), "RIGHT"),
            ("ALIGN",         (0, 1), (1, -1), "LEFT"),
            ("TOPPADDING",    (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ("LEFTPADDING",   (0, 0), (-1, -1), 8),
            ("RIGHTPADDING",  (0, 0), (-1, -1), 8),
            ("BOX",           (0, 0), (-1, -1), 0.8, _BORDER),
            ("LINEBELOW",     (0, 0), (-1, -1), 0.3, _BORDER),
        ]
        for i, (row_idx, is_gain) in enumerate(zip(range(1, len(holdings)+1), h_pl_signs)):
            bg = _CARD_BG if i % 2 == 0 else _ROW_ALT
            h_style.append(("BACKGROUND", (0, row_idx), (-1, row_idx), bg))
            h_style.append(("TEXTCOLOR",  (6, row_idx), (6, row_idx), _GREEN if is_gain else _RED))
            h_style.append(("FONTNAME",   (6, row_idx), (6, row_idx), "Helvetica-Bold"))
        h_tbl.setStyle(TableStyle(h_style))
        story.append(_section_header("Holdings", styles))
        story.append(Spacer(1, 6))
        story.append(h_tbl)
        story.append(Spacer(1, 16))

    # ── Transactions Table ────────────────────────────────────────────────────
    if transactions:
        tx_color_map = {"Buy": _GREEN, "Sell": _RED, "Dividend": _YELLOW}
        tx_headers = ["Date", "Symbol", "Type", "Qty", "Price", "Total Value"]
        tx_rows = [tx_headers]
        tx_types = []
        for tx in transactions[:10]:
            tx_types.append(tx["type"].capitalize())
            tx_rows.append([
                tx.get("date", "—")[:10],
                tx["symbol"].replace(".NS", "").replace(".BO", ""),
                tx["type"].capitalize(),
                f"{tx['quantity']:g}",
                f"₹{tx['price']:,.2f}",
                f"₹{tx['quantity'] * tx['price']:,.0f}",
            ])

        tx_tbl = Table(tx_rows, colWidths=[2.6*cm, 3.2*cm, 2*cm, 1.8*cm, 3.7*cm, 3.7*cm])
        tx_style = [
            ("BACKGROUND",    (0, 0), (-1, 0), _NAVY),
            ("TEXTCOLOR",     (0, 0), (-1, 0), _WHITE),
            ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE",      (0, 0), (-1, -1), 8),
            ("ALIGN",         (0, 0), (-1, 0), "CENTER"),
            ("ALIGN",         (3, 1), (-1, -1), "RIGHT"),
            ("TOPPADDING",    (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ("LEFTPADDING",   (0, 0), (-1, -1), 8),
            ("RIGHTPADDING",  (0, 0), (-1, -1), 8),
            ("TEXTCOLOR",     (0, 1), (-1, -1), _TEXT),
            ("BOX",           (0, 0), (-1, -1), 0.8, _BORDER),
            ("LINEBELOW",     (0, 0), (-1, -1), 0.3, _BORDER),
        ]
        for i, (row_idx, tx_type) in enumerate(zip(range(1, len(tx_types)+1), tx_types)):
            bg = _CARD_BG if i % 2 == 0 else _ROW_ALT
            tx_style.append(("BACKGROUND", (0, row_idx), (-1, row_idx), bg))
            col = tx_color_map.get(tx_type, _TEXT)
            tx_style.append(("TEXTCOLOR",  (2, row_idx), (2, row_idx), col))
            tx_style.append(("FONTNAME",   (2, row_idx), (2, row_idx), "Helvetica-Bold"))
        tx_tbl.setStyle(TableStyle(tx_style))
        story.append(_section_header("Recent Transactions", styles))
        story.append(Spacer(1, 6))
        story.append(tx_tbl)

    # ── Disclaimer ────────────────────────────────────────────────────────────
    story.append(Spacer(1, 20))
    disc = Table([[Paragraph(
        "This report is generated for informational purposes only. "
        "Past performance is not indicative of future results. "
        "All prices are indicative and sourced from public data feeds.",
        ParagraphStyle("Disc", parent=styles["Normal"], textColor=_MUTED, fontSize=7, leading=10),
    )]], colWidths=[17*cm])
    disc.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), _SECTION),
        ("BOX",           (0, 0), (-1, -1), 0.5, _BORDER),
        ("LEFTPADDING",   (0, 0), (-1, -1), 10),
        ("TOPPADDING",    (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(disc)

    doc.build(story)
    return buf.getvalue()


@router.get("/portfolio/{client_id}")
async def get_portfolio_report(client_id: str, manager=Depends(require_manager)):
    """Generate and return a PDF portfolio report for a client."""
    supabase = get_supabase_admin()

    # Verify client belongs to this manager
    try:
        client_result = (
            supabase.table("users")
            .select("*")
            .eq("id", client_id)
            .eq("manager_id", manager.id)
            .single()
            .execute()
        )
    except Exception:
        raise HTTPException(status_code=404, detail="Client not found or not assigned to you")
    if not client_result.data:
        raise HTTPException(status_code=404, detail="Client not found or not assigned to you")
    client = client_result.data

    # Fetch manager name
    try:
        mgr_result = (
            supabase.table("users").select("full_name").eq("id", manager.id).single().execute()
        )
        manager_name = mgr_result.data.get("full_name", "Manager") if mgr_result.data else "Manager"
    except Exception:
        manager_name = "Manager"

    # Fetch portfolios
    portfolios_result = (
        supabase.table("portfolios").select("id").eq("client_id", client_id).execute()
    )
    portfolio_ids = [p["id"] for p in (portfolios_result.data or [])]
    if not portfolio_ids:
        raise HTTPException(status_code=404, detail="No portfolios found for this client")

    # Fetch holdings from first/only portfolio
    holdings_result = (
        supabase.table("holdings")
        .select("*")
        .in_("portfolio_id", portfolio_ids)
        .execute()
    )
    holdings = holdings_result.data or []

    # Fetch transactions (most recent 10)
    transactions_result = (
        supabase.table("transactions")
        .select("*")
        .in_("portfolio_id", portfolio_ids)
        .order("date", desc=True)
        .limit(10)
        .execute()
    )
    transactions = transactions_result.data or []

    # Fetch live prices for stock/ETF holdings in parallel
    tradeable_symbols = list({
        h["symbol"] for h in holdings
        if h.get("asset_type") in ("stock", "etf")
    })
    loop = asyncio.get_running_loop()
    price_tasks = [
        loop.run_in_executor(None, _fetch_price, sym)
        for sym in tradeable_symbols
    ]
    price_results = await asyncio.gather(*price_tasks)
    live_prices: dict[str, float] = {
        sym: price
        for sym, price in zip(tradeable_symbols, price_results)
        if price is not None
    }

    # Generate PDF in thread pool (reportlab is sync)
    pdf_bytes = await loop.run_in_executor(
        None,
        _generate_pdf,
        manager_name,
        client,
        holdings,
        transactions,
        live_prices,
    )

    client_name_safe = client.get("full_name", "client").replace(" ", "_")
    filename = f"portfolio_{client_name_safe}_{date.today().isoformat()}.pdf"

    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename={filename}"},
    )
